// node test/bridge-runner.mjs  (J387: the per-job runner's command line, pure; the live runs are in docker/bridge/README.md)
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { plan } from "../docker/bridge/runner.mjs";
const d = fs.mkdtempSync(path.join(os.tmpdir(), "j387-"));
const job = { id: "door-t--a00001", approved: { action: "Request drafted by D for A.\nAction asked for: write hello", tools: ["Write", "Bash(git status)", "Read; rm -rf /", "x".repeat(60)], folders: [d, "/nonexistent/x", "relative/dir"], time_limit_s: 600 }, questions: [{ n: 1, text: "Which file?", answer: "out.txt" }, { n: 2, text: "open?", answer: null }] };
const p = plan(job, { mcpConfig: "/tmp/m.json", model: "" });
const at = (f) => p.argv[p.argv.indexOf(f) + 1];
assert.equal(p.argv[0], "claude"); assert.ok(p.argv.includes("-p") && p.argv.includes("--no-session-persistence") && p.argv.includes("--restricted") && p.argv.includes("--strict-mcp-config"));
assert.equal(at("--mcp-config"), "/tmp/m.json"); assert.equal(at("--permission-mode"), "dontAsk");
assert.equal(at("--tools"), "Write,Bash", "built-in tools: exactly the job's (base names)");
const allowed = at("--allowedTools").split(",");
assert.ok(allowed.includes("Write") && allowed.includes("Bash(git status)"), "the job's tools with their rules");
assert.ok(!allowed.some((t) => /claim_job|release_job|propose|read_settings/.test(t)), "the agent can't claim, release or touch settings");
assert.deepEqual(p.dropped, ["Read; rm -rf /", "x".repeat(60)], "odd tool names are dropped, not passed");
assert.deepEqual(p.argv.filter((a, i) => p.argv[i - 1] === "--add-dir"), [d], "only existing absolute folders");
assert.equal(p.cwd, d);
assert.ok(!p.argv.includes(p.prompt) && !p.argv.some((a) => /write hello/.test(a)), "the prompt isn't an argument (it goes on stdin)");
assert.match(p.prompt, /----- the owner's approved text -----\nRequest drafted by D for A\.\nAction asked for: write hello\n----- end -----/);
assert.match(p.prompt, /Q1: Which file\?\nA1: out\.txt/); assert.ok(!/open\?/.test(p.prompt), "only answered questions");
const none = plan({ ...job, approved: { ...job.approved, tools: [], folders: [] } }, { mcpConfig: "/tmp/m.json" });
assert.equal(none.argv[none.argv.indexOf("--tools") + 1], "", "no built-in tools at all when the job names none");
assert.ok(!none.argv.includes("--add-dir")); assert.equal(none.cwd, os.tmpdir());
process.env.DOORMAN_RUNNER_CMD = '["/opt/agent","--x"]'; assert.deepEqual(plan(job, { mcpConfig: "m" }).argv.slice(0, 3), ["/opt/agent", "--x", "-p"]);
fs.rmSync(d, { recursive: true, force: true }); console.log("bridge-runner: all pass");
