// trackHeld (Doorman window "now:" row): where a decided held request went, from the relay's own pending folder and log.
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "held-track-"));
process.env.XDG_STATE_HOME = tmp;
const S = path.join(tmp, "hyprpi", "sbx-relay"); fs.mkdirSync(path.join(S, "pending"), { recursive: true });
const { trackHeld } = await import("../lib/held.mjs");
const log = (...a) => fs.appendFileSync(path.join(S, "log.jsonl"), a.map((x) => JSON.stringify({ t: new Date().toISOString(), ...x })).join("\n") + "\n");
fs.writeFileSync(path.join(S, "pending", "w--aaaaaa.json"), "{}");
assert.equal(trackHeld("w--aaaaaa").state, "pending"); assert.equal(trackHeld("w--aaaaaa").done, false);
assert.equal(trackHeld("w--bbbbbb").state, "gone");
assert.equal(trackHeld("../x").done, true);
log({ sb: "w", op: "research", decision: "approved", id: "w--cccccc", delivered: ["w"], file: "research-q1.md" });
let t = trackHeld("w--cccccc"); assert.equal(t.state, "approved"); assert.ok(t.done); assert.match(t.text, /delivered into w: research-q1\.md/);
log({ sb: "w", op: "talk", decision: "denied", id: "w--dddddd" });
t = trackHeld("w--dddddd"); assert.equal(t.state, "denied"); assert.match(t.text, /nothing was sent/);
log({ sb: "w", op: "research-plan", decision: "approved", id: "w--eeeeee", rid: "q2", delivered: ["the research runner (searches started)"], searches: ["a", "b"] });
t = trackHeld("w--eeeeee"); assert.equal(t.done, false); assert.match(t.text, /2 searches went to the research runner/);
log({ sb: "w", op: "research", token: "r1", status: "ready", rid: "q2" });
t = trackHeld("w--eeeeee"); assert.equal(t.done, false); assert.match(t.text, /held for your review/);
log({ sb: "w", op: "research", decision: "approved", id: "w--ffffff", delivered: ["w"], file: "research-q2.md" });
t = trackHeld("w--eeeeee"); assert.ok(t.done); assert.match(t.text, /approved and delivered into w: research-q2\.md/);
log({ sb: "w", op: "research-plan", decision: "approved", id: "w--444444", rid: "q3", delivered: ["the research runner (searches started)"], searches: ["a"] });
log({ sb: "w", op: "research", decision: "denied", id: "w--555555", rid: "q3" });
t = trackHeld("w--444444"); assert.ok(t.done); assert.match(t.text, /deliverable was denied/);
log({ sb: "d", op: "gpu_lease", decision: "approved", id: "d--111111", lease: "g1" });
t = trackHeld("d--111111"); assert.equal(t.done, false); assert.match(t.text, /running \(or queued\)/);
log({ sb: "d", op: "gpu_lease", lease: "g1", status: "ok", exit: 0, ranSeconds: 1.2, peakVramMib: 0, delivered: "gpu-g1.md" });
t = trackHeld("d--111111"); assert.ok(t.done); assert.match(t.text, /finished: ok, exit 0, ran 1\.2 s.*gpu-g1\.md/);
log({ sb: "w", op: "talk", decision: "approved", id: "w--222222", delivered: ["Lenswatch (B6)"] });
t = trackHeld("w--222222"); assert.ok(t.done); assert.match(t.text, /delivered to Lenswatch/);
log({ sb: "w", op: "talk", decision: "approved", id: "w--333333", error: "inbox full" });
assert.match(trackHeld("w--333333").text, /couldn't carry it out: inbox full/);
fs.rmSync(tmp, { recursive: true, force: true });
console.log("held-track: all pass");
