// node test/modellist.mjs  (J397: the scoped model list as the only list: matching rules, Kimi refused by the list alone, routing models audited)
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { unsupportedPatterns, allowedBy, notAllowed, auditPolicy, readList, removeModel, setKnownModels } from "../lib/modellist.mjs";
import { loadPolicy } from "../lib/policy.mjs";
const ok = (m) => console.log("ok " + m);
setKnownModels(["anthropic/claude-opus-5-5", "nv-inference/a/b/c", "nvidia/openai/gpt-oss-20b", "nvidia/openai/gpt-oss-120b", "anthropic/a/b", "openrouter/foo/bar", "anything/at-all"]);
const L = ["anthropic/*", "openai-codex/*", "nv-inference/**", "nvidia/openai/gpt-oss-20b"];
assert.equal(allowedBy("anthropic/claude-opus-5-5", L), "anthropic/*"); assert.equal(allowedBy("anthropic/claude-opus-5-5:high", L), "anthropic/*", "thinking suffix ignored");
assert.equal(allowedBy("Anthropic/Claude-Opus-5-5", L), "anthropic/*", "case-insensitive");
assert.equal(allowedBy("nv-inference/a/b/c", L), "nv-inference/**", "** crosses slashes"); assert.equal(allowedBy("anthropic/a/b", L), "", "* stays in one segment");
assert.equal(allowedBy("nvidia/openai/gpt-oss-20b", L), "nvidia/openai/gpt-oss-20b"); assert.equal(allowedBy("nvidia/openai/gpt-oss-120b", L), "", "exact entries are exact");
assert.equal(allowedBy("claude-opus-5-5", L), "anthropic/*", "a bare id matches through a listed provider");
assert.equal(allowedBy("openrouter/foo/bar", L), ""); assert.equal(allowedBy("", L), ""); assert.equal(allowedBy("anything/at-all", []), "*", "no list = all models (pi's rule)");
ok("matching rules: exact, globs (* / **), case, thinking suffix, bare ids, empty list");
// (J397 review) bare ids resolve to what pi knows; pi's looser patterns; failures close
setKnownModels(["anthropic/foo", "testprov/kimi-test", "testprov/org/b", "a/dup", "b/dup"]);
assert.equal(allowedBy("kimi-test", ["anthropic/*"]), "", "a bare id that pi would resolve outside the list is refused");
assert.equal(allowedBy("foo", ["anthropic/*"]), "anthropic/*"); assert.equal(allowedBy("dup", ["a/*"]), "", "ambiguous: every meaning must be listed"); assert.equal(allowedBy("dup", ["a/*", "b/*"]), "a/*");
assert.equal(allowedBy("org/b", ["testprov/**"]), "testprov/**", "a nested bare id"); assert.equal(allowedBy("nope", ["anthropic/*"]), "", "unknown bare id: fail closed");
assert.equal(allowedBy("anthropic/foo", ["foo"]), "", "a bare non-glob name is unsupported: allows nothing (pi picks ONE model by fuzzy lookup)"); assert.deepEqual(unsupportedPatterns(["foo", "a/b", "fo*"]), ["foo"]);
assert.ok(allowedBy("anthropic/foo", ["fo*"]) && allowedBy("anthropic/foo", ["*"]) && allowedBy("testprov/kimi-test", ["testprov/[ac]*"]) === "" && allowedBy("anthropic/foo", ["anthropic/[ef]*"]), "pi's bare/fuzzy/class patterns");
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "j397u-")), f = path.join(tmp, "s.json");
fs.writeFileSync(f, "{ not json"); process.env.PI_CODING_AGENT_DIR = tmp; fs.renameSync(f, path.join(tmp, "settings.json"));
assert.throws(() => readList(), /doesn't parse/); assert.equal(readList(path.join(tmp, "missing.json")).length, 0, "no file = no list");
const g = path.join(tmp, "g.json"); fs.writeFileSync(g, JSON.stringify({ enabledModels: ["p/*", "q/keep"] }), { mode: 0o600 });
process.env.HYPRPI_PI = "/bin/false"; setKnownModels(null); assert.throws(() => removeModel("p/bad", { file: g }), /failed or listed nothing/); assert.deepEqual(JSON.parse(fs.readFileSync(g, "utf8")).enabledModels, ["p/*", "q/keep"], "a failed listing changes nothing");
setKnownModels(["p/bad", "p/good"]); assert.throws(() => removeModel("q/keep", { file: g, protect: ["keep"] }), /protected/);
removeModel("p/bad", { file: g }); assert.equal(fs.statSync(g).mode & 0o777, 0o600, "file mode kept"); assert.deepEqual(JSON.parse(fs.readFileSync(g, "utf8")).enabledModels, ["p/good", "q/keep"]);
setKnownModels(["testprov/a", "testprov/claude-test", "testprov/anthropic/evil", "anthropic/real"]);
assert.equal(allowedBy("anthropic/unknown-to-pi", ["anthropic/*"]), "", "an identity pi doesn't list: fail closed");
assert.equal(allowedBy("testprov/a", ["testprov/[!a]*"]), "", "[!a] negates"); assert.equal(allowedBy("testprov/claude-test", ["testprov/[!a]*"]), "testprov/[!a]*"); assert.equal(allowedBy("testprov/a", ["testprov/[^b]*"]), "testprov/[^b]*", "[^b] negates");
setKnownModels(["testprov/a", "testprov/ab", "testprov/axc", "testprov/a/c", "testprov/a/b/c", "testprov/anthropic/evil", "nv-inference/x/y", "nv-inference/z"]);
const only = (pat) => ["testprov/a", "testprov/ab", "testprov/axc", "testprov/a/c", "testprov/a/b/c", "testprov/anthropic/evil", "nv-inference/x/y", "nv-inference/z"].filter((m) => allowedBy(m, [pat]));
assert.deepEqual(only("testprov/a**"), ["testprov/a", "testprov/ab", "testprov/axc"], "** inside a segment stays in the segment");
assert.deepEqual(only("testprov/a[^b]c"), ["testprov/axc"], "a class never matches /"); assert.deepEqual(only("testprov/**c"), ["testprov/axc"], "**c is segment-local");
assert.deepEqual(only("nv-inference/**"), ["nv-inference/x/y", "nv-inference/z"], "a whole-segment ** crosses slashes"); assert.deepEqual(only("testprov/**/c"), ["testprov/a/c", "testprov/a/b/c"].filter((m) => only("testprov/**/c").includes(m)), "middle **");
assert.ok(allowedBy("testprov/a/b/c", ["testprov/**/c"]) && allowedBy("testprov/c", ["testprov/**/c"]) === "" , "** between segments matches several segments");
setKnownModels(["testprov/a.c", "testprov/a0c", "testprov/a/c"]); assert.equal(allowedBy("testprov/a/c", ["testprov/a[.-0]c"]), "", "a class RANGE spanning / never matches /"); assert.ok(allowedBy("testprov/a0c", ["testprov/a[.-0]c"]) && allowedBy("testprov/a.c", ["testprov/a[!b]c"]));
setKnownModels(null); process.env.HYPRPI_PI = "/bin/false"; assert.equal(allowedBy("anthropic/evil", ["anthropic/*"]), "", "no registry: fail closed"); delete process.env.HYPRPI_PI;
setKnownModels(["testprov/a", "testprov/claude-test", "testprov/anthropic/evil", "anthropic/real"]);
assert.equal(allowedBy("testprov/claude-test", ["a"]), "", "no substring matching of a bare pattern"); assert.equal(allowedBy("testprov/a", ["a"]), "", "and a bare name allows nothing at all (unsupported, never wrongly broad)");
assert.equal(allowedBy("anthropic/evil", ["anthropic/*"]), "", "a qualified-looking id that pi resolves to another provider is refused"); assert.equal(allowedBy("anthropic/real", ["anthropic/*"]), "anthropic/*");
fs.writeFileSync(g, JSON.stringify({ enabledModels: ["p/bad"] })); assert.throws(() => removeModel("p/bad", { file: g }), /leave the list empty/); assert.deepEqual(JSON.parse(fs.readFileSync(g, "utf8")).enabledModels, ["p/bad"]);
setKnownModels(["p/bad", "p/good"]);
ok("bare ids resolve (fail closed), pi's bare/fuzzy/class patterns, an unreadable settings file throws, a failed pi listing and a protected model change nothing, the file mode is kept");
// Kimi is refused by the list alone, with the real host list
setKnownModels(null); delete process.env.HYPRPI_PI; delete process.env.PI_CODING_AGENT_DIR;
const real = readList(); assert.ok(real.length > 0, "the host has a list");
for (const k of ["nvidia/moonshotai/kimi-k3", "nvidia/moonshotai/kimi-k2.6", "openrouter/~moonshotai/kimi-latest", "openrouter/moonshotai/kimi-k2"]) assert.equal(allowedBy(k, real), "", k + " is not on the host list");
assert.equal(loadPolicy().modelDeny, undefined, "hyprpi.jsonc has no modelDeny any more");
assert.match(notAllowed("nvidia/moonshotai/kimi-k3", "anthropic/claude-sonnet-5-5"), /not on the host's scoped model list.*Use anthropic\/claude-sonnet-5-5 instead/);
ok("Kimi (all four) is refused by the host list alone; no modelDeny");
// every routing / thoughts model is on the list
assert.deepEqual(auditPolicy(loadPolicy(), real), [], "every model hyprpi.jsonc names is on the list");
setKnownModels(["anthropic/x", "nvidia/q/w", "foo/bar", "openrouter/y/z"]);
assert.deepEqual(auditPolicy({ routing: { ladder: ["anthropic/x:low", "openrouter/y/z:high"], kinds: { a: "nvidia/q/w" } }, thoughts: { model: "foo/bar" } }, L).map((b) => b.where), ["routing.ladder[1]", "routing.kinds.a", "thoughts.model"], "the audit finds the ones that aren't");
ok("the audit: every model in the live hyprpi.jsonc is on the list, and it finds unlisted ones in a made-up policy");
console.log("modellist: all pass");
