export const REFUSED = "how does humidity degrade MAPbI3 (methylammonium lead iodide perovskite)? Explain molecular mechanisms, reversible hydration versus irreversible decomposition, reaction equations where established, effects of relative humidity/time/temperature/light/oxygen, and consequences for solar-cell performance. Cite primary research with source URLs; distinguish established findings from disputed or condition-dependent mechanisms.";
export const GOOD = [
  "Compare the thermal stability of CH₃NH₃PbI₃ and HC(NH₂)₂PbI₃ (FAPbI₃) at 85 °C/85% RH: onset of decomposition, products (PbI₂, CH₃NH₂, HI) and how encapsulation changes it.",
  "What drives the α-FAPbI3 → δ-FAPbI3 phase transition under humidity, and how do Cs⁺ or MA⁺ additions (e.g. Cs0.05FA0.95PbI3) stabilise the black phase?",
  "Summarise stability data for triple-cation Cs0.05(FA0.83MA0.17)0.95Pb(I0.83Br0.17)3 cells under 1-sun illumination at 65 °C, including T80 lifetimes and the main degradation pathways.",
  "How do ion migration and halide segregation in mixed-halide MAPb(I1−xBrx)3 films depend on light intensity, temperature and humidity? Include activation energies in eV where reported.",
  "Explain the hydrate intermediates (CH3NH3)4PbI6·2H2O and CH3NH3PbI3·H2O that form when MAPbI3 meets water vapour, and which steps are reversible.",
  "Which encapsulation stacks (glass/glass with butyl edge seal, PIB, EVA, POE, ALD Al2O3) let perovskite modules pass IEC 61215 damp heat (85 °C/85% RH, 1000 h)?",
  "Device architecture comparison: FTO/SnO2/perovskite/Spiro-OMeTAD/Au versus ITO/PTAA/perovskite/C60/BCP/Ag for thermal and humidity stability.",
  "What role does PbI2 excess play in MAPbI3 and FAPbI3 film stability, and does residual PbI2 accelerate photodegradation under 1 sun?",
  "Precursor chemistry: how do PbI2/MAI/DMF/DMSO solvent systems and antisolvents like chlorobenzene affect grain size (in μm) and trap density (cm⁻³) of perovskite films?",
  "Report efficiency records for perovskite–silicon tandem cells (certified, 2023–2025) and the stability evidence that accompanied them.",
  "How does Sn²⁺ oxidation to Sn⁴⁺ limit the stability of tin-lead perovskites such as FA0.5MA0.5Pb0.5Sn0.5I3, and which additives (SnF2, metallic Sn powder) help?",
  "Effect of 2D/3D heterostructures (PEA2PbI4 or BA2PbI4 capping layers on FAPbI3) on moisture resistance and efficiency.",
  "Water contact angle and moisture ingress for hydrophobic hole transport layers (PTAA, P3HT, CuSCN) compared with Spiro-OMeTAD doped with Li-TFSI and tBP.",
  "What is known about the degradation of NiOx/perovskite interfaces at 85 °C in inverted p-i-n cells, and how do self-assembled monolayers (2PACz, Me-4PACz) change it?",
  "Reaction equations for MAPbI3 decomposition: CH3NH3PbI3 → PbI2 + CH3NH2 + HI and the role of oxygen and light (superoxide O2⁻ formation).",
  "Outdoor stability: how do diurnal temperature cycling (−40 °C to 85 °C) and humidity freeze tests affect perovskite modules?",
  "Which characterisation methods (XRD, PL, TRPL, XPS, ToF-SIMS) best detect early humidity degradation in perovskite films, with typical signatures?",
  "Bandgap tuning of CsPbI3 and CsPbI2Br inorganic perovskites (1.7–1.9 eV) for thermal stability versus phase stability at room humidity.",
  "Compare ISOS-L-2 and ISOS-D-3 stability protocols for perovskite cells and which results are comparable across labs.",
  "How do Lewis-base passivators (e.g. thiophene, pyridine, phenethylammonium iodide PEAI) reduce non-radiative recombination and improve humidity tolerance?",
  "Humidity-assisted crystallisation: does 30–40% RH during annealing improve MAPbI3 or FAPbI3 film quality, and at what point does moisture start degrading it?",
  "Lead leakage from damaged perovskite modules in rain: measured Pb²⁺ release (mg/m²) and encapsulants that capture lead (P,P′-di(2-ethylhexyl)methanediphosphonic acid).",
  "Thermal expansion mismatch between perovskite layers and glass/ITO substrates: does it cause delamination during 200 thermal cycles?",
  "Efficiency loss mechanisms in FAPbI3/MAPbBr3 bilayers under light soaking: hysteresis, J–V scan rate and maximum power point tracking results.",
  "What do accelerated aging tests at 85 °C, 1 sun, N₂ atmosphere show about the intrinsic thermal stability of MA-free compositions like Cs0.1FA0.9PbI3?",
];
export const BAD = [
  ["perovskite stability QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVo0NTY3", "a long encoded-looking string"],
  ["perovskite aGVsbG8vd29ybGQvZm9vL2Jhcg== stability", "a long encoded-looking string"],
  ["MAPbI3 humidity xq7vplm/zrt9kqwe/bnm4lpoi/qwerty77 degradation", "a long encoded-looking string"],
  ["degradation of PbI2/aGVsbG8gd29ybGQgZm9vYmFy/bGQ= films", "a long encoded-looking string"],
  ["CsPbI3 stability Zm9vYmFyYmF6cXV4cXV1eHF1dXg", "a long encoded-looking string"],
  ["perovskite deadbeefcafebabe1234 films", "a long hex string"],
  ["CsPbI3 films ₁₂₃₄₅₆₇₈₉₀₁₂₃₄₅₆₇", "a long run of digits"],
  ["humidity tests 4111 1111 1111 1111 22", "a long run of digits"],
  ["perоvskite humidity (Cyrillic о)", "mixed scripts (look-alike letters)"],
  ["MAPbI3 kxqzt/vbnmw/plkjh/gfdsa/zxcvb/qwrtp", "a long encoded-looking string"],
  ["stability of Ab3Cd4Ef5Gh6Ij7Kl8Mn9Op0Qr1St2", "a long encoded-looking string"],
  ["perovskite sk-abcdefghijklmnop stability", "a key or token"],
];
